CreateDefaultXML<-function(ParametersValues,AdvancedParametersValues,HOpath="./")
{
  #
  sink(file.path(HOpath,"HO.xml"))
  cat("<?xml version=\"1.0\"?>\n<HUB-OPT version=\"1.0\">\n")
  cat("<HUB-OPT>\n")
  cat("\t<GENERAL_OPTIONS>\n")
  cat("\t\t<!--debug mode: 0 no display, debug displays, -1 no simulation display-->\n")
  cat("\t\t<PRINT_DEBUG_MODE>0</PRINT_DEBUG_MODE>\n")
  cat("\t\t<!--display level:<0 mute, =0 def value (20), >=1 display error, >=10 display warnings, >=20 display info, >=30 display debug-->\n")
  cat("\t\t<DISPLAY_LEVEL>",AdvancedParametersValues$print_level,"</DISPLAY_LEVEL>\n")
  if (AdvancedParametersValues$print_level > 10) {cat("\t\t<SAVE_PERF_FILES>1</SAVE_PERF_FILES>\n")} else {cat("\t\t<SAVE_PERF_FILES>0</SAVE_PERF_FILES>\n")}
  cat("\t</GENERAL_OPTIONS>\n")
  cat("\t<OPTIMIZATION>\n")
  cat("\t\t<!--0 (standard formulation), 1(nonlinear least-squares formulation), 2(nonlinear system of equations)-->\n")
  cat("\t\t<FORMULATION>0</FORMULATION>\n")
  cat("\t\t<!-- 0(SQPAL)  1(SQA)  2(CMAES)  3(DONLP2)  4(IPOPT)  5(PORT)  6(BOBYQA)  7(COBYLA)  8(MCMC)  9(NEWUOA)  10(MOCMAES)  11(NLOPT)  12(BOMA)  13(MINPACK)  14(MULTISTART)  15(EGO)  16(LBFGSb)  17(GOSGRID)  18(NSGAII)  19(SQA_PSOF)  20(TUNELLING)  21(NOMAD)  22(REGO) -->\n")
  solver = as.character(ParametersValues$solver)
  if (solver == "SQPAL") {
    cat("\t\t<SOLVER>0</SOLVER>\n")
    } else if (solver == "SQA") {
    cat("\t\t<SOLVER>1</SOLVER>\n")
    } else if (solver == "CMAES") {
      cat("\t\t<SOLVER>2</SOLVER>\n")
    } else if (solver == "COBYLA") {
      cat("\t\t<SOLVER>7</SOLVER>\n")
    } else if (solver == "NEWUOA") {
      cat("\t\t<SOLVER>9</SOLVER>\n")
    } else if (solver == "MULTI-START") {
      cat("\t\t<SOLVER>14</SOLVER>\n")
    } else if (solver == "EGO") {
      cat("\t\t<SOLVER>15</SOLVER>\n")
    } else if (solver == "L-BFGSb") {
      cat("\t\t<SOLVER>16</SOLVER>\n")
    } else if (solver == "NSGA2") {
      cat("\t\t<SOLVER>18</SOLVER>\n")
    } else if (solver == "NOMAD") {
      cat("\t\t<SOLVER>21</SOLVER>\n")
    } else if (solver == "MCMC") {
      cat("\t\t<SOLVER>8</SOLVER>\n")
    } else {
      cat("\t\t<SOLVER>1</SOLVER>\n")
  }
  
  cat("\t\t<PERTURBATION>\n")
  cat("\t\t\t<!--relative maximal parameter perturbation-->\n")
  cat("\t\t\t<MAX>1</MAX>\n")
  cat("\t\t\t<!--relative minimal parameter perturbation-->\n")
  cat("\t\t\t<MIN>",as.character(ParametersValues$dx_min),"</MIN>\n")
  cat("\t\t\t<!--relative initial parameter perturbation-->\n")
  cat("\t\t\t<INI>",as.character(ParametersValues$dx_init),"</INI>\n")
  cat("\t\t</PERTURBATION>\n")
  cat("\t\t<GRADIENTS>\n")
  cat("\t\t\t<!--0 (Default user gradient), 1 (FD HubOpt gradient), 2 (DOE HubOpt gradient), 3 (EFD HubOpt gradient)-->\n")
  cat("\t\t\t<GRADIENT_MODE>1</GRADIENT_MODE>\n")
  cat("\t\t\t<!--step length for gradient computation by finite differences: if 0 automatic tuning-->\n")
  cat("\t\t\t<FINITE_DIFF_STEP>0</FINITE_DIFF_STEP>\n")
  cat("\t\t\t<!--relative threshold on the maximum finite difference step length with respect to the maximal parameter perturbation-->\n")
  cat("\t\t\t<FINITE_DIFF_THRESHOLD>0.1</FINITE_DIFF_THRESHOLD>\n")
  cat("\t\t\t<!--0 (inactive opportunistic mode), 1 (active opportunistic mode)-->\n")
  cat("\t\t\t<OPPORTUNISTIC_MODE>1</OPPORTUNISTIC_MODE>\n")
  cat("\t\t\t<!--0 (cheap gradients), 1 (evaluation of gradients is time consumming)-->\n")
  cat("\t\t\t<CHEAP_GRADIENTS>1</CHEAP_GRADIENTS>\n")
  cat("\t\t</GRADIENTS>\n")
  cat("\t\t<HESSIAN>\n")
  cat("\t\t\t<!--initialization of Hessian matrix: 0(no initial Hessian defined), 1(user-defined initial Hessian), 2(HubOpt initial Hessian)-->\n")
  cat("\t\t\t<INIT_HESSIAN>2</INIT_HESSIAN>\n")
  cat("\t\t</HESSIAN>\n")
  cat("\t\t<NORMALIZATION>\n")
  cat("\t\t\t<!--normalisation of cost function: 0(no normalisation), 1(HubOpt obj. func. normalisation), 2(user defined obj. func. normalization)-->\n")
  cat("\t\t\t<OBJ_FUNC_NORM>0</OBJ_FUNC_NORM>\n")
  cat("\t\t\t<!--normalisation of parameters: 0(no normalisation), 1(HubOpt parameter normalisation), 2(user defined parameter normalization)-->\n")
  cat("\t\t\t<UNKNOWN_NORM>2</UNKNOWN_NORM>\n")
  cat("\t\t</NORMALIZATION>\n")
  cat("\t\t<STOPPING_CRITERION>\n")
  cat("\t\t\t<!--maximum number of simulations-->\n")
  cat("\t\t\t<MAX_NB_SIMUL>",ParametersValues$maxeval,"</MAX_NB_SIMUL>\n")
  cat("\t\t</STOPPING_CRITERION>\n")
  cat("\t</OPTIMIZATION>\n")
  cat("</HUB-OPT>\n")
  cat("<SOLVERS>\n")
  if (solver == "SQPAL" || (solver == "MULTI-START" && as.character(ParametersValues$localsolver) == "SQPAL" )) {
    cat("\t<SQPAL>\n")
    cat("\t\t<!--maximum number of SQP iterations-->\n")
    cat("\t\t<MAX_NB_SQP_ITER>1000</MAX_NB_SQP_ITER>\n")
    cat("\t\t<!--Hessian approximation : 0 (BFGS), 1(BFGS_Powell) , 2(GN), 3(user-defined Hessian)-->\n")
    cat("\t\t<HESSIAN_APPROX>1</HESSIAN_APPROX>\n")
    cat("\t\t<!--rescale of Hessian matrix (active only for BFGS): 0 (no rescale) 1(rescale at first iteration and when necessary)-->\n")
    cat("\t\t<HESSIAN_RESCALE>0</HESSIAN_RESCALE>\n")
    cat("\t\t<!--0(Line Search Armijo_Han), 1(Dog-Leg Trust Region), 2(Levenberg-marquardt), 3(Dog-Leg L-infinite norm Trust Region)-->\n")
    cat("\t\t<GLOBALIZATION>0</GLOBALIZATION>\n")
    cat("\t\t<!--max nb of line-search/trust-region iterations-->\n")
    cat("\t\t<MAX_NB_GLOBALIZATION_ITER>10</MAX_NB_GLOBALIZATION_ITER>\n")
    cat("\t</SQPAL>\n")
  }
  if (solver == "SQA" || (solver == "MULTI-START" && as.character(ParametersValues$localsolver) == "SQA" )) {
	  cat("\t<SQA>\n")
	  cat("\t\t<!--Number of interpolation points used to build SQA models in [nx+2,(nx+1)(nx+2)/2] : 0 default value=(2nx+1), -1 min value=(nx+2), -2 max value=0.5(nx+1)(nx+2), -3 mean value=0.25(nx_+2)(nx_+3)-->\n")
	  cat("\t\t<NB_INTERPOL_PT>",AdvancedParametersValues$npoints,"</NB_INTERPOL_PT>\n")
	  cat("\t\t<!--SQA Least-square mode: 0=normal mode  1=LS mode(1 model for each square of residual) 2=LS mode(1 model for each residual)-->\n")
	  cat("\t\t<LSmode>0</LSmode>\n")
	  cat("\t\t<!--Weight for merit function in cae of difficult constraints-->\n")
	  cat("\t\t<WEIGHT_MERIT>",AdvancedParametersValues$weightMerit,"</WEIGHT_MERIT>\n")
	  cat("\t\t<!--Display level (0:none)-->\n")
	  cat("\t\t<DISP_LEVEL>0</DISP_LEVEL>\n")
	  cat("\t\t<!--Number of parallel simulation runs [1]-->\n")
	  cat("\t\t<NB_PARALLEL_RUNS>1</NB_PARALLEL_RUNS>\n")
	  cat("\t</SQA>\n")
  }
  if (solver == "CMAES") {
	  cat("\t<CMAES>\n")
	  cat("\t\t<!--maximal number of generations-->\n")
	  cat("\t\t<MAX_NB_GENERATIONS>10000000</MAX_NB_GENERATIONS>\n")
	  cat("\t\t<!--initial standard deviation (same value for each parameter), default 0,3-->\n")
	  cat("\t\t<INIT_SIGMA>0.3</INIT_SIGMA>\n")
	  cat("\t\t<!--stop if std dev increases more than by this value, default 1e3-->\n")
	  cat("\t\t<STOP_UP_X_FACTOR>1000</STOP_UP_X_FACTOR>\n")
	  cat("\t\t<!--target value for objective function (default: -HUGE_VAL)-->\n")
	  cat("\t\t<FTARGET>-2.14748e+009</FTARGET>\n")
	  cat("\t\t<!--random seed (default:0) if <>0 seed is fixed to this value-->\n")
	  cat("\t\t<SEED>",as.character(AdvancedParametersValues$seed),"</SEED>\n")
	  cat("\t\t<!--population size  (default: 4+3*ln(nx) -->\n")
	  cat("\t\t<LAMBDA>",AdvancedParametersValues$npoints,"</LAMBDA>\n")
	  cat("\t\t<!--number of selected search points in the population (default: lambda/3) )-->\n")
	  cat("\t\t<MU>0</MU>\n")
	  cat("\t\t<!--Constraint mode: 0=none 1=reject 2=penalization (default: 1) )-->\n")
	  cat("\t\t<CONSTRAINT_MODE>1</CONSTRAINT_MODE>\n")
	  cat("\t\t<!--Max distance from bounds (mode=2): reject points that are too far from bounds % of distance[bmin,bmax] (default: 20) )-->\n")
	  cat("\t\t<PMAX>20</PMAX>\n")
	  cat("\t\t<!--Use of a metamodel (by default:0 no metamodel) 1:kriging-->\n")
	  cat("\t\t<METAMODEL>0</METAMODEL>\n")
	  cat("\t\t<!--Ranking method (by default:0) choice:0 or 1-->\n")
	  cat("\t\t<RANKING_METHOD>0</RANKING_METHOD>\n")
	  cat("\t\t<!--Ranking method with EI (by default:0) choice:0 or 1-->\n")
	  cat("\t\t<RANKING_EI>0</RANKING_EI>\n")
	  cat("\t\t<!--Nb of initial points in ranking procedure (0:by default lambda)-->\n")
	  cat("\t\t<NB_INITIAL_POINTS>0</NB_INITIAL_POINTS>\n")
	  cat("\t\t<!--Nb of simulated points per iteration of ranking procedure (0:by default 1)-->\n")
	  cat("\t\t<NB_POINTS_PER_ITER>0</NB_POINTS_PER_ITER>\n")
	  cat("\t\t<!--Injection of external solutions (0: none by default, -1: CMAES best-ever solution)-->\n")
	  cat("\t\t<SOL_INJECTION>0</SOL_INJECTION>\n")
	  cat("\t</CMAES>\n")
  }
  if (solver == "MULTI-START") {
	  cat("\t<MULTISTART>\n")
	  cat("\t\t<!--Number of initial points chosen with a LHS DOE-->\n")
	  cat("\t\t<NB_INITIAL_POINTS>",ParametersValues$nx0,"</NB_INITIAL_POINTS>\n")
	  cat("\t\t<!--Local solver: 0 (SQPAL), 1(SQA) -->\n")
	  Localsolver = as.character(ParametersValues$localsolver)
	  cat("\t\t<MS_SOLVER>1</MS_SOLVER>\n")
	  if (Localsolver == "SQPAL") {
	     cat("\t\t<MS_SOLVER>0</MS_SOLVER>\n")
	  } 
	  cat("\t\t<!--Display level for internal optimizations-->\n")
	  cat("\t\t<MS_DISP_LEVEL>-1</MS_DISP_LEVEL>\n")
	  cat("\t\t<!--Set LHS seed-->\n")
	  cat("\t\t<LHS_SEED>",as.character(AdvancedParametersValues$seed),"</LHS_SEED>\n")
	  cat("\t</MULTISTART>\n")
  }
  if (solver == "NSGAII") {
    cat("\t<NSGAII>\n")
    cat("\t\t<!--maximal number of generations [1000] >=1-->\n")
    cat("\t\t<MAX_NB_GENERATIONS>1000</MAX_NB_GENERATIONS>\n")
    cat("\t\t<!--random seed (default:0.5) 0<value<1-->\n")
    cat("\t\t<SEED>0</SEED>\n")
    cat("\t\t<!--population size [4] >=4 and a multiple of 4-->\n")
    cat("\t\t<POPSIZE>4</POPSIZE>\n")
    cat("\t\t<!--probability of crossing for real parameters 0<=value<=1 [0.5]-->\n")
    cat("\t\t<PCROSS_REAL>0.5</PCROSS_REAL>\n")
    cat("\t\t<!--probability of mutation for real parameters 0<=value<=1 [0.5]-->\n")
    cat("\t\t<PMUT_REAL>0.5</PMUT_REAL>\n")
    cat("\t\t<!--value of distribution index for crossover >0 (5-20) [5]-->\n")
    cat("\t\t<ETA_CROSS>5</ETA_CROSS>\n")
    cat("\t\t<!--value of distribution index for mutation >0 (5-50) [5]-->\n")
    cat("\t\t<ETA_MUT>5</ETA_MUT>\n")
    cat("\t</NSGAII>\n")
  }
  if (solver == "EGO") {
	  cat("<EGO>\n")
	  cat("<NB_INITIAL_POINTS>",ParametersValues$nx0,"</NB_INITIAL_POINTS>\n")
	  cat("<MAX_NB_POINTS_PER_ITER>",ParametersValues$nx_iter,"</MAX_NB_POINTS_PER_ITER>\n")
	  cat("</EGO>\n")
  }
  if (solver == "MCMC") {
    cat("\t<MCMC>\n")
    cat("\t\t<!--Number of initial points for initial Space Filling design of experiments-->\n")
    cat("\t\t<NB_INITIAL_POINTS>",ParametersValues$nx0,"</NB_INITIAL_POINTS>\n")
    cat("\t\t<!--Number of sampling points-->\n")
    cat("\t\t<NB_SAMPLE_POINTS>",AdvancedParametersValues$nSampling,"</NB_SAMPLE_POINTS>\n")
    cat("\t\t<!--Max number of additionnal points at each iter-->\n")
    cat("\t\t<MAX_NB_POINTS_PER_ITER>",ParametersValues$nx_iter,"</MAX_NB_POINTS_PER_ITER>\n")
    cat("\t\t<!--Number of additionnal points at each iter according to the EIG criterion-->\n")
    cat("\t\t<NB_POINTS_EIG>",AdvancedParametersValues$nEI_iter,"</NB_POINTS_EIG>\n")
	cat("\t\t<!--random seed (default:0) if <>0 seed is fixed to this value-->\n")
    cat("\t\t<SEED>",AdvancedParametersValues$seed,"</SEED>\n")
    cat("\t\t<!--size of the LHS used to compute the kriging parameters with the multi-start optimization-->\n")
    cat("\t\t<NTHETA>",AdvancedParametersValues$nTheta,"</NTHETA>\n")
	  cat("\t</MCMC>\n")
  }
  cat("</SOLVERS>\n")
  cat("</HUB-OPT>\n")
  sink()
  #}
  
  return
}

  
  